create or replace TABLE SUSANOO.PUBLIC.WEATHER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CITY VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	BASE VARCHAR(16777216) NOT NULL,
	DESCRIPTION VARCHAR(16777216) NOT NULL,
	TIME NUMBER(38,0) NOT NULL,
	TEMPERATURE FLOAT NOT NULL,
	MIN_TEMP FLOAT NOT NULL,
	MAX_TEMP FLOAT NOT NULL,
	PRESSURE NUMBER(38,0) NOT NULL,
	HUMIDITY NUMBER(38,0) NOT NULL,
	VISIBILITY NUMBER(38,0) NOT NULL,
	WIND_SPEED FLOAT NOT NULL,
	WIND_DEG NUMBER(38,0) NOT NULL,
	primary key (ID)
);

create or replace TABLE SUSANOO.PUBLIC.POLLUTION (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CITY VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	TIME NUMBER(38,0) NOT NULL,
	AQI NUMBER(38,0) NOT NULL,
	CO FLOAT NOT NULL,
	NO FLOAT NOT NULL,
	NO2 FLOAT NOT NULL,
	O3 FLOAT NOT NULL,
	SO2 FLOAT NOT NULL,
	PM2_5 FLOAT NOT NULL,
	PM10 FLOAT NOT NULL,
	NH3 FLOAT NOT NULL,
	primary key (ID)
);

create or replace TABLE SUSANOO.PUBLIC.CITIES (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CITY VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	TIMEZONE NUMBER(38,0) NOT NULL,
	primary key (ID)
);